version: '3.8'

services:
  backend:
    build:
      context: ./server  # Adjust if your backend folder is named differently
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client  # Adjust if your frontend folder is named differently
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
